### PR TITLE
Support for plural HSE commands

### PR DESCRIPTION
**Pull request by jmarsik**
For reading multiple variables of the same type in single round-trip, i.e. faster. With convenient `read_variables` method that handles separation of variables of the same type and with consecutive numbers for plural command usage.

### CODE REVIEW

**Comment by hsinkoyu** [comment]
Thank you very much for your contribution. I like the idea of inputting list of FS100.Variable for read_variables() and concatenate the consecutive variable number ones for a single HSE plural command. Thanks.

**Comment by hsinkoyu** [comment]
Hi Jakub,
I just committed [Precisely followed the spec to implement variables read/write.](https://github.com/hsinkoyu/fs100/commit/3ee518b83bb4d002259f9318e50985fbc313baa2),
so we could revert [handle string variables without plural commands, as single reads](https://github.com/hsinkoyu/fs100/commit/96ba9904a6bc390935240f13fb12dadd8ba40aac),
right?
I have tested the changes and it worked well.

**Comment by jmarsik** [comment]
Hello Hsinko,
does that mean that now it's possible to read string and position variables with plural commands? I didn't study the documentation that much for those types because we do not use them... If that's the case, then the commit could be reverted. I can do a PR for that if you want.

**Comment by hsinkoyu** [comment]
Reading string and position variables with plural commands is OK now. You decide whether to revert the commit or pend it till
#8 completes.

**Pull request merged**
